- Esc + A --> ABOVE
- Esc + B --> BELOW

- Esc + M --> markDown

* TO SEE DESCRIPTION OF METHOD
    - Shift + Tab
    - method ?
    - Help Description

DATA ANALYST
DATA

- This is First Class of Pandas
- In Python, Everthing is Object

In [ ]:
Numpy, Pandas--> 20 Hours

In [44]:
pd.Series(data= [234,34,32,34,45], index=['AAA','B','C','D','E'])

AAA    234
B       34
C       32
D       34
E       45
dtype: int64

In [ ]:
PANDAS

1D Array - Series   [23,45,7,6789,90]
2D Matrix - Data Frame [ [ ]
                         [ ] ]
3D Tensor - Panel

In [2]:
import numpy as np
import pandas as pd

np.array?

In [ ]:
pip install pandas

In [95]:
#from pandas import Series

import pandas as pd 

ser = pd.Series( data = [23,45,67,], index=["Abhinav","Komal","Shalu"])
print(ser)
#print(type(ser)) # Type of object 
#print(ser.index) # Index
#print(ser.values) # Values

# --> INDEXING / SLICING
ser[100:300]

Abhinav    23
Komal      45
Shalu      67
dtype: int64


Series([], dtype: int64)

In [34]:
import pandas as pd # alias
obj = pd.Series(  [3,6,9,12,15,18] )
obj

print("INDEX -->", obj.index)
print("VALUES-->", obj.values)

# Indexing / Slicing ?


<class 'pandas.core.series.Series'>


Series([], dtype: int64)

In [10]:
obj.values

array([ 3,  6,  9, 12], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=6, step=1)

In [11]:
obj[2]

9

In [23]:
list = range(1,7)                                                 

In [76]:
s

SyntaxError: invalid syntax (<ipython-input-76-d2634a84b397>, line 1)

In [96]:
import numpy as np
np.NaN

nan

In [97]:
ww = pd.Series(  [870000,43000000,   3000000,    210000, np.NAN], 
               index = ['USSR','Germany','China','Japan','USA'] )
ww[2]

USSR         870000.0
Germany    43000000.0
China       3000000.0
Japan        210000.0
USA               NaN
dtype: float64

In [98]:
ww['China']

3000000.0

In [99]:
ww[2]

3000000.0

In [103]:
ww > 2000000

USSR       False
Germany     True
China       True
Japan      False
USA        False
dtype: bool

In [104]:
ww[ ww > 2000000  ]

Germany    43000000.0
China       3000000.0
dtype: float64

in Operator  --> Membership Operator 

In [105]:
's' in 'Sourabh'

False

In [59]:
12 in [12,34,56,2]

True

In [106]:
ww

USSR         870000.0
Germany    43000000.0
China       3000000.0
Japan        210000.0
USA               NaN
dtype: float64

In [1]:
210000.0 in ww

NameError: name 'ww' is not defined

In [109]:
ww.index

Index(['USSR', 'Germany', 'China', 'Japan', 'USA'], dtype='object')

In [110]:
ww.values

array([  870000., 43000000.,  3000000.,   210000.,       nan])

In [111]:
'USA' in ww.index

True

In [115]:
870000.0 in ww  #ww.index

False

In [114]:
870000.0 in ww.values

True

In [118]:
print(ww)
type(ww)

USSR         870000.0
Germany    43000000.0
China       3000000.0
Japan        210000.0
USA               NaN
dtype: float64


pandas.core.series.Series

In [68]:
ww2_dict = ww.to_dict()   # Series --> Dict
ww2_dict

{'USSR': 87000.0,
 'Germany': 430000.0,
 'China': 3000.0,
 'Japan': 2100.0,
 'USA': nan}

In [69]:
ww2_series = pd.Series(ww2_dict)  # Dict --> Series
ww2_series

USSR        87000.0
Germany    430000.0
China        3000.0
Japan        2100.0
USA             NaN
dtype: float64

In [3]:
import numpy as np
np.NaN

nan

In [2]:
NaN

NameError: name 'NaN' is not defined

In [119]:
ww

USSR         870000.0
Germany    43000000.0
China       3000000.0
Japan        210000.0
USA               NaN
dtype: float64

In [123]:
pd.isnull(ww)

USSR       False
Germany    False
China      False
Japan      False
USA         True
dtype: bool

In [124]:
pd.notnull(ww)

USSR        True
Germany     True
China       True
Japan       True
USA        False
dtype: bool

In [125]:
#BROADCASTING
ww + 10

USSR         870010.0
Germany    43000010.0
China       3000010.0
Japan        210010.0
USA               NaN
dtype: float64

In [5]:
np.NaN * 12

nan

In [126]:
#must have same index
ww2_series

USSR        87000.0
Germany    430000.0
China        3000.0
Japan        2100.0
USA             NaN
dtype: float64

In [128]:
ww

USSR         870000.0
Germany    43000000.0
China       3000000.0
Japan        210000.0
USA               NaN
dtype: float64

In [129]:
ww2_series + ww

USSR         957000.0
Germany    43430000.0
China       3003000.0
Japan        212100.0
USA               NaN
dtype: float64

In [130]:
ww.name = 'WW2 Casualties'
ww

USSR         870000.0
Germany    43000000.0
China       3000000.0
Japan        210000.0
USA               NaN
Name: WW2 Casualties, dtype: float64

In [134]:
ww.index.name = 'COUNTRIES'

In [135]:
ww

COUNTRIES
USSR         870000.0
Germany    43000000.0
China       3000000.0
Japan        210000.0
USA               NaN
Name: WW2 Casualties, dtype: float64

In [136]:
ww.index

Index(['USSR', 'Germany', 'China', 'Japan', 'USA'], dtype='object', name='COUNTRIES')

In [138]:
ww.values

array([  870000., 43000000.,  3000000.,   210000.,       nan])

In [132]:
type(ww.index)

pandas.core.indexes.base.Index

In [137]:
type(ww.values)

numpy.ndarray